title: FIAT TIPO AUTOPADOVA
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.9981203
  lightness: 0.6875
  brandColors:
    - '#FDFDFD'
    - '#42010F'
    - '#919299'
    - '#383B41'
    - '#BDBEC5'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: FIAT TIPO
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2504962009843439
layout_spectrum: 0.7274436
